/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-10-30 15:57:41 UTC)
 * on 2013-11-13 at 11:48:10 UTC 
 * Modify at your own risk.
 */

package com.appspot.appusagemonitor.appusagemonitor.model;

/**
 * ProtoRPC message definition to represent a score that is stored.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the appusagemonitor. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AppusagemonitorApiMessagesScoreResponseMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String outcome;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String played;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public AppusagemonitorApiMessagesScoreResponseMessage setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getOutcome() {
    return outcome;
  }

  /**
   * @param outcome outcome or {@code null} for none
   */
  public AppusagemonitorApiMessagesScoreResponseMessage setOutcome(java.lang.String outcome) {
    this.outcome = outcome;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPlayed() {
    return played;
  }

  /**
   * @param played played or {@code null} for none
   */
  public AppusagemonitorApiMessagesScoreResponseMessage setPlayed(java.lang.String played) {
    this.played = played;
    return this;
  }

  @Override
  public AppusagemonitorApiMessagesScoreResponseMessage set(String fieldName, Object value) {
    return (AppusagemonitorApiMessagesScoreResponseMessage) super.set(fieldName, value);
  }

  @Override
  public AppusagemonitorApiMessagesScoreResponseMessage clone() {
    return (AppusagemonitorApiMessagesScoreResponseMessage) super.clone();
  }

}
