/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-10-30 15:57:41 UTC)
 * on 2013-11-13 at 11:48:10 UTC 
 * Modify at your own risk.
 */

package com.appspot.appusagemonitor.appusagemonitor.model;

/**
 * ProtoRPC message definition to represent a score to be inserted.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the appusagemonitor. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AppusagemonitorApiMessagesAppUsageRequestMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime appEndTime;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String appName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime appStartTime;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String packageName;

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getAppEndTime() {
    return appEndTime;
  }

  /**
   * @param appEndTime appEndTime or {@code null} for none
   */
  public AppusagemonitorApiMessagesAppUsageRequestMessage setAppEndTime(com.google.api.client.util.DateTime appEndTime) {
    this.appEndTime = appEndTime;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAppName() {
    return appName;
  }

  /**
   * @param appName appName or {@code null} for none
   */
  public AppusagemonitorApiMessagesAppUsageRequestMessage setAppName(java.lang.String appName) {
    this.appName = appName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getAppStartTime() {
    return appStartTime;
  }

  /**
   * @param appStartTime appStartTime or {@code null} for none
   */
  public AppusagemonitorApiMessagesAppUsageRequestMessage setAppStartTime(com.google.api.client.util.DateTime appStartTime) {
    this.appStartTime = appStartTime;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPackageName() {
    return packageName;
  }

  /**
   * @param packageName packageName or {@code null} for none
   */
  public AppusagemonitorApiMessagesAppUsageRequestMessage setPackageName(java.lang.String packageName) {
    this.packageName = packageName;
    return this;
  }

  @Override
  public AppusagemonitorApiMessagesAppUsageRequestMessage set(String fieldName, Object value) {
    return (AppusagemonitorApiMessagesAppUsageRequestMessage) super.set(fieldName, value);
  }

  @Override
  public AppusagemonitorApiMessagesAppUsageRequestMessage clone() {
    return (AppusagemonitorApiMessagesAppUsageRequestMessage) super.clone();
  }

}
