/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-02-14 18:40:25 UTC)
 * on 2014-03-10 at 22:55:41 UTC 
 * Modify at your own risk.
 */

package com.appspot.appusagemonitor.appusagemonitor.model;

/**
 * ProtoRPC message definition to represent a list of AppUsage records.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the appusagemonitor. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AppusagemonitorApiMessagesAppUsageInsertRequest extends com.google.api.client.json.GenericJson {

  /**
   * ProtoRPC message definition to represent a appusage rec to be inserted.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<AppusagemonitorApiMessagesAppUsageRecord> items;

  /**
   * ProtoRPC message definition to represent a appusage rec to be inserted.
   * @return value or {@code null} for none
   */
  public java.util.List<AppusagemonitorApiMessagesAppUsageRecord> getItems() {
    return items;
  }

  /**
   * ProtoRPC message definition to represent a appusage rec to be inserted.
   * @param items items or {@code null} for none
   */
  public AppusagemonitorApiMessagesAppUsageInsertRequest setItems(java.util.List<AppusagemonitorApiMessagesAppUsageRecord> items) {
    this.items = items;
    return this;
  }

  @Override
  public AppusagemonitorApiMessagesAppUsageInsertRequest set(String fieldName, Object value) {
    return (AppusagemonitorApiMessagesAppUsageInsertRequest) super.set(fieldName, value);
  }

  @Override
  public AppusagemonitorApiMessagesAppUsageInsertRequest clone() {
    return (AppusagemonitorApiMessagesAppUsageInsertRequest) super.clone();
  }

}
