/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-10-30 15:57:41 UTC)
 * on 2013-11-13 at 11:48:10 UTC 
 * Modify at your own risk.
 */

package com.appspot.appusagemonitor.appusagemonitor.model;

/**
 * ProtoRPC message definition to represent a list of stored AppUsage records.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the appusagemonitor. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AppusagemonitorApiMessagesAppUsageListResponse extends com.google.api.client.json.GenericJson {

  /**
   * ProtoRPC message definition to represent a AppUsage that is stored.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<AppusagemonitorApiMessagesAppUsageResponseMessage> items;

  static {
    // hack to force ProGuard to consider AppusagemonitorApiMessagesAppUsageResponseMessage used, since otherwise it would be stripped out
    // see http://code.google.com/p/google-api-java-client/issues/detail?id=528
    com.google.api.client.util.Data.nullOf(AppusagemonitorApiMessagesAppUsageResponseMessage.class);
  }

  /**
   * ProtoRPC message definition to represent a AppUsage that is stored.
   * @return value or {@code null} for none
   */
  public java.util.List<AppusagemonitorApiMessagesAppUsageResponseMessage> getItems() {
    return items;
  }

  /**
   * ProtoRPC message definition to represent a AppUsage that is stored.
   * @param items items or {@code null} for none
   */
  public AppusagemonitorApiMessagesAppUsageListResponse setItems(java.util.List<AppusagemonitorApiMessagesAppUsageResponseMessage> items) {
    this.items = items;
    return this;
  }

  @Override
  public AppusagemonitorApiMessagesAppUsageListResponse set(String fieldName, Object value) {
    return (AppusagemonitorApiMessagesAppUsageListResponse) super.set(fieldName, value);
  }

  @Override
  public AppusagemonitorApiMessagesAppUsageListResponse clone() {
    return (AppusagemonitorApiMessagesAppUsageListResponse) super.clone();
  }

}
